---
title: Normal by nature? An annotated example of a normally distributed variable
author: Sebastian Sauer
draft: TRUE
date: '2021-06-22'
slug: normal-by-nature-an-annotated-example-of-a-normally-distributed-variable
categories:
  - rstats
tags:
  - tutorial
---




# Setup


```{r}
library(tidyverse)
library(ggpubr)
```


```{r}
d <- read_csv("https://vincentarelbundock.github.io/Rdatasets/csv/openintro/speed_gender_height.csv")
```



# Histogram of height


```{r}
d2 <-
  d |> 
  select(-gender)
```

```{r}
d_summary <-
  d %>% 
  group_by(gender) %>% 
  summarise(height_m = mean(height, na.rm = T),
            height_sd = sd(height, na.rm = T))

d_summary
```



```{r}
d |> 
  ggplot() +
  aes() +
  geom_histogram(aes(y = ..density.., x = height, fill = gender)) +
  facet_wrap(~ gender) +
  geom_histogram(data = d2, aes(y = ..density.., x = height), alpha = .5) +
  stat_function(data = d_summary %>% filter(gender == "female"),
                fun = dnorm,
                #color = "red",
                args = list(mean = filter(d_summary, gender == "female")$height_m,
                            sd = filter(d_summary, gender == "female")$height_sd)) +
  stat_function(data = d_summary %>% filter(gender == "male"),
                fun = dnorm,
                #color = "red",
                args = list(mean = filter(d_summary, gender == "male")$height_m,
                            sd = filter(d_summary, gender == "male")$height_sd)) +
  scale_fill_discrete()
   
```

A bit more beautifully perhaps:


```{r}
gghistogram(d,
            x = "height", 
            fill = "gender",
            rug = TRUE,
            add_density = TRUE,
            add = "mean")
```

# For the whole sample

I.e,. with groups (gender) removed:

```{r}
gghistogram(d,
            x = "height",
            add_density = TRUE,
            add = "mean")
```


# Checking the fit to a normal curve

## For the whole group (no subgroups)

```{r}
d %>% 
  ggplot() +
  aes(sample = height) +
  geom_qq() +
  stat_qq_line()
```


## For each gender (group) separately



```{r}
d %>% 
  ggplot() +
  aes(sample = height) +
  geom_qq(alpha = .7) +
  facet_wrap(~ gender) +
  stat_qq_line(linetype = "dashed")
```