baseurl = "/"
languageCode = "en-us"
title = "sesa blog"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = "https-data-se-netlify-com"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
enableEmoji = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Data privacy"
    url = "/privacy/"
[[menu.main]]
    name = "Tags"
    url = "/tags/"



[social]
    github  = "https://github.com/sebastian_sauer"
    twitter = "https://twitter.com/sauer_sebastian"


[params]
    description = "Sebastian Sauer's statistics blog"
    name = "Sebastian Sauer"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
    highlight = true
    highlight_languages = ["r", "yaml"]
    highlight_style = "atelier-cave-light"



    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo-data-se.png"
    width = 50
    height = 50
    alt = "Logo"

