---
title: Tables, plotted as ggplot objects
author: Sebastian Sauer
date: '2023-02-03'
slug: tables-plotted-as-ggplot-objects
categories:
  - rstats
tags:
  - visualization
  - ggplot2
output:
  blogdown::html_page:
    toc: yes
    number_sections: yes
---



```{r knitr-setup, echo = FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  message = FALSE,
  warning = FALSE,
  cache = TRUE,
  out.width = "100%",
  fig.align = 'center',
  fig.width = 6,
  fig.asp = 0.618,  # 1 / phi
  fig.show = "hold",
  size = "tiny"
)
```



# Load packages

```{r load-libs, message = FALSE, warning = FALSE}
library(tidyverse)  # data wrangling
library(gridExtra)
library(grid)
library(gt)
library(ggpubr)
```



# Show case 1: grid.table


```{r}
d <- head(iris[,1:3])
grid.table(d)
```

`grid.table` does the job nicely.

Just plotting give a somewhat too raw object:

```{r}
plot(tableGrob(d))
```


# Show case 2: tableGrob

The following R code is taken [from this source](https://stackoverflow.com/questions/68517917/r-ggplot-and-gt-outputs-how-can-i-combine-these-on-an-output-image):



```{r}
GGP <- ggplot(dat = iris, aes( x= Sepal.Width, y = Sepal.Length, colour = Species)) + geom_point() 

tab <- 
  iris %>% 
  group_by(Species) %>% 
  summarise(n = n(), Mean = mean(Sepal.Width), SD = sd(Sepal.Width))

grid.arrange(GGP,tableGrob(tab))
```

# Show case 3: Reduce whitespace

Let's get rid of white space.

```{r}
x <- data.frame(a=1, b= 2)
ss <- tableGrob(x)

   #Make a scatterplot of your data
k <- ggplot(x,aes(x=x$"Value 1",y=x$"Value 2")) + 
   geom_point()

   #Arrange them as you want with grid.arrange
grid.arrange(ss)
```

```{r}
mytheme <- gridExtra::ttheme_default(
             core = list(padding=unit(c(1, 1), "mm"))
           )
mytable <- tableGrob(mtcars, theme = mytheme)
grid.arrange(mytable)
```

# Show case 4: ggpubr

The package `ggpubr` offers some nice capabilities for plotting tables as ggplot objects:

```{r}
library(ggpubr)
ggpubr::ggtexttable(head(mtcars), rows = NULL)
```



# Reproducibility

```{r reproducibility, echo = FALSE}
## Reproducibility info
options(width = 120)
devtools::session_info()

```


