---
title: Bayes-Software installieren für R
author: Sebastian Sauer
date: '2022-01-28'
slug: bayes-software-installieren-für-r
categories:
  - rstats
tags:
  - tutorial
---




# R und seine Freunde installieren.



Schauen Sie, dass Sie zuerst [R und seine Freunde](https://data-se.netlify.app/2021/11/30/installation-von-r-und-seiner-freunde/) installiert haben.


# Bayes-Software

Bayes-Inferenz kann rechenintensiv sein.
Daher braucht's Software, die schnell rechnen kann.
Außerdem sollte die Software sich gut mit Wahrscheinlichkeitsrechnung auskennen,
denn Bayes ist nichts anderes als angewandte Wahrscheinlichkeitsrechnung.

Aktuell ist die Software [Stan](https://mc-stan.org/) die führende Software für diesen Zweck.

Bevor Sie aber  Stan installieren können, brauchen Sie eine (Software für eine) 
"schnelle Rechenmaschine" auf Ihrem Computer installiert.
Stan nutzt dafür C++.

Um C++ zu installieren gehen Sie so vor:

- Mac: Installieren Sie die [Command Line Tools](https://macpaw.com/how-to/install-command-line-tools);
viele Anleitungen finden sich dafür online.
- Windows: Installieren Sie die [Rtools](https://cran.rstudio.com/bin/windows/Rtools/)
- Linux: Schauen Sie mal auf die [Seite von Stan](https://github.com/stan-dev/rstan/wiki/Configuring-C-Toolchain-for-Linux)


Wenn C++ installiert ist, ist das Schwierigste geschafft.

Jetzt können Sie in gewohnter Weise die restliche Software - d.i. vor allem Stan -  als R-Pakete installieren:


```{r eval = FALSE}
pckgs_bayes <-
  c("rstan",
    "rstanarm",
    "bayesplot",
    "bayestestR",
    "tidybayes")

install.packages(pckgs_bayes)
```


`rstan` ist ein R-Paket, das Stan und eine Verbindung zu Stan von R bereitstellt.
Die übrigen Pakete greifen alle auf Stan zurück,
bieten aber komfortable Zusatzfunktionen wie Visualisierungen und vereinfachte Syntax.


