---
title: 'Datensatz flights: Finde den Tag mit den meisten Abflügen'
author: Sebastian Sauer
date: '2021-05-27'
slug: datensatz-flights-finde-den-tag-mit-den-meisten-abflügen
categories:
  
tags:
  - datawrangling
output:
  blogdown::html_page:
    toc: yes
    number_sections: yes
---



```{r knitr-setup, echo = FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  message = FALSE,
  warning = FALSE,
  cache = TRUE,
  out.width = "100%",
  fig.align = 'center',
  fig.width = 6,
  fig.asp = 0.618,  # 1 / phi
  fig.show = "hold",
  size = "tiny"
)
```




# Aufgabe: Finde den Tag mit den meisten Abflügen (`flights`)!


An welchem Tag im Jahr 2013 sind die meisten Flüge aus NYC gestartet?



# Setup

```{r}
library(tidyverse)  # Datenjudo
library(nycflights13)  # Daten
library(lubridate)  # Datumsangaben
```


# Daten laden

```{r}
data(flights)
```



# Spalte mit Datum ergänzen


```{r}
flights <-
  flights %>% 
  mutate(date = date(time_hour))
```


# Datensatz zusammenfassen


```{r}
flights2 <-
  flights %>% 
  group_by(date) %>% 
  summarise(n = n())
```


Synonym:



```{r}
flights2 <-
  flights %>% 
  count(date)
```



# Maximalwert der Spalte `n`


```{r}
flights2 %>% 
  slice_max(n)
```

