---
title: A quick demo how to compute rowwise means with the tidyverse
author: Sebastian Sauer
date: '2023-01-16'
slug: a-quick-demo-how-to-compute-rowwise-means-with-the-tidyverse
categories:
  - rstats
tags:
  - tidyverse
  - datawrangling
output:
  blogdown::html_page:
    toc: yes
    number_sections: yes
---



```{r knitr-setup, echo = FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  message = FALSE,
  warning = FALSE,
  cache = TRUE,
  out.width = "100%",
  fig.align = 'center',
  fig.width = 6,
  fig.asp = 0.618,  # 1 / phi
  fig.show = "hold",
  size = "tiny"
)
```



# Load packages

```{r load-libs, message = FALSE, warning = FALSE}
library(tidyverse)  # data wrangling
```

# Motivation


Sometimes is is neccessary to compute functions, such as mean values, rowwise, ie., summing the values for multiple variables (`my_vars`) for each observation.



# Minimal example

For the sake of simplicity, we'll make use of the `mtcars` dataset.



```{r}
data(mtcars)

my_vars <- c("mpg", "cyl", "hp")

mtcars <-
  mtcars |> 
  select(all_of(my_vars)) |> 
  rowwise() |> 
  mutate(mtcars_score = mean(c_across(all_of(my_vars)), na.rm = TRUE))

head(mtcars)  # check
```

Check:

```{r}
(21+6+110) / 3
```


# See also

- [Help page of `rowwise`](https://dplyr.tidyverse.org/articles/rowwise.html)
- [application on SO](https://stackoverflow.com/questions/31375835/dplyr-error-with-rowwise-mutate-with-na)
- [alternatives and demo]()

# Reproducibility

```{r reproducibility, echo = FALSE}
## Reproducibility info
options(width = 120)
devtools::session_info()

```


